# Generated by Django 3.1.5 on 2021-01-16 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_passsenger'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Passsenger',
            new_name='Passenger',
        ),
    ]
